// svelte-ids-wc/src/examples/ids-modal/Index.svelte
<script>
    import { onMount } from 'svelte';
    import 'ids-enterprise-wc/components/ids-modal';
    
    // Supporting Components
    import 'ids-enterprise-wc/components/ids-button';
    import 'ids-enterprise-wc/components/ids-icon';
    import 'ids-enterprise-wc/components/ids-text';
    import 'ids-enterprise-wc/components/ids-layout-grid';

    let modal;
    let triggerBtn;

    onMount(() => {
        // Connect the Modal and its Button when the Svelte component is mounted (sets up click/focus events)
        modal.target = triggerBtn;
        modal.trigger = 'click';

        // Disable the trigger button when showing the Modal.
        modal.addEventListener('beforeshow', () => {
            triggerBtn.disabled = true;
            return true;
        });

        // Close the modal when its inner button is clicked.
        modal.onButtonClick = () => {
            modal.hide();
        };

        // After the modal is done hiding, re-enable its trigger button.
        modal.addEventListener('hide', () => {
            triggerBtn.disabled = false;
        });
    });
</script>

<style></style>

<ids-layout-grid>
    <ids-text font-size="12">Modal (Svelte)</ids-text>
</ids-layout-grid>

<ids-modal
    id="test-modal"
    bind:this={modal}>
    <ids-text slot="title" font-size="24" type="h2" id="my-modal-title">Active IDS Modal</ids-text>
    <ids-modal-button slot="buttons" id="modal-close-btn" type="primary">
        <span slot="text">OK</span>
    </ids-modal-button>
    <p align="left">This is an active IDS Modal component</p>
</ids-modal>

<ids-layout-grid>
    <ids-layout-grid-cell>
        <ids-button
            id="test-modal-trigger-btn"
            type="secondary"
            bind:this={triggerBtn}>Show Modal</ids-button>
    </ids-layout-grid-cell>
</ids-layout-grid>

// react-ids-wc/src/examples/ids-modal/index.js
import React, { useRef } from 'react';

import 'ids-enterprise-wc/components/ids-modal/ids-modal';

const IdsModal = () => {
  const modalRef = useRef();

  return (
    <>
      <ids-modal ref={modalRef} aria-labelledby="my-modal-title">
        <ids-text slot="title" font-size="24" type="h2" id="my-modal-title">
          Active IDS Modal
        </ids-text>
        <ids-modal-button
          slot="buttons"
          type="primary"
          onClick={() => {
            modalRef.current?.hide()
          }}
        >
          <span slot="text">OK</span>
        </ids-modal-button>
        <ids-text type="p">This is an active IDS Modal component</ids-text>
      </ids-modal>

      <ids-layout-grid auto="true">
        <ids-text font-size="12" type="h1">
          Modal
        </ids-text>
      </ids-layout-grid>
      <ids-layout-grid auto="true">
        <ids-layout-grid-cell>
          <ids-button
            type="secondary"
            // Trigger ids-modal visibility with React onClick synthetic event
            onClick={() => {
              modalRef.current?.show()
            }}
            disabled={modalRef.current?.visible}
          >
            <span slot="text">Trigger a Modal</span>
          </ids-button>
        </ids-layout-grid-cell>
      </ids-layout-grid>
    </>
  );
};

export default IdsModal;
