// react-ts-ids-wc/src/examples/ids-color/index.tsx
import React from 'react';
import 'ids-enterprise-wc/components/ids-color/ids-color';


const IdsColor = () => {
  return (
    <>
      <ids-layout-grid auto="true">
        <ids-text font-size="12" type="h1">
          Color
        </ids-text>
      </ids-layout-grid>

      <ids-layout-grid auto="true">
        <ids-color hex="#da9e2d"></ids-color>
      </ids-layout-grid>
    </>
  );
};

export default IdsColor;

// sveltekit-ids-wc/src/routes/ids-color/index.svelte
<script lang="ts">
  import IdsDemoListing from '../../components/demo/IdsDemoListing.svelte';

  const listingData = [
    {
      link: 'example',
      type: 'Main Example',
      description: 'Shows color swatches'
    }
  ];
</script>

<ids-layout-grid auto="true">
  <ids-text font-size="20" type="h1">Ids Color Examples</ids-text>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <IdsDemoListing data={listingData} componentName="ids-color"></IdsDemoListing>
  </ids-layout-grid-cell>
</ids-layout-grid>
