// sveltekit-ids-wc/src/routes/ids-tabs/vertical.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  onMount(async (): Promise<void> => {
    await Promise.all([
      import('ids-enterprise-wc/components/ids-tabs/ids-tab'),
      import('ids-enterprise-wc/components/ids-tabs/ids-tabs')
    ]);
  });

  const handleChange = (e: Event | CustomEvent | any) => {
    console.info(`ids-tabs.on('change') =>`, e.target?.value);
  };
</script>

<ids-tabs value="notes" orientation="vertical" id="ids-tabs-vertical">
  <ids-tab value="contracts" on:change={handleChange}>Contracts</ids-tab>
  <ids-tab value="opportunities" on:change={handleChange}>Opportunities</ids-tab>
  <ids-tab value="attachments" disabled on:change={handleChange}>Attachments</ids-tab>
  <ids-tab value="notes" on:change={handleChange}>Notes</ids-tab>
</ids-tabs>

// angular-ids-wc/src/app/components/ids-tabs/demos/vertical/vertical.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-vertical',
  templateUrl: './vertical.component.html',
  styleUrls: ['./vertical.component.css']
})
export class VerticalComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<ids-tabs value="notes" orientation="vertical" id="ids-tabs-vertical">
  <ids-tab value="contracts">Contracts</ids-tab>
  <ids-tab value="opportunities">Opportunities</ids-tab>
  <ids-tab value="attachments" disabled>Attachments</ids-tab>
  <ids-tab value="notes">Notes</ids-tab>
</ids-tabs>
