// react-ids-wc/src/components/ids-input/index.js
import React from 'react';

import 'ids-enterprise-wc/components/ids-layout-grid';
// import 'ids-enterprise-wc/components/ids-input';

const IdsInput = () => {
  const person = 'John Smith';

  function handleClickable(e) {
    console.log('Input Changed', e.target);
  }

  return (
    <>
      <ids-layout-grid>
        <ids-text font-size="12">Inputs</ids-text>
      </ids-layout-grid>

      <ids-layout-grid>
        <ids-layout-grid-cell>
          <ids-input label="Normal Input" value={ person } onChange={ handleClickable }></ids-input>
        </ids-layout-grid-cell>
      </ids-layout-grid>
    </>
  );
}

export default IdsInput;

// sveltekit-ids-wc/src/components/ids-input/IdsInput.svelte
<script>
    import { createEventDispatcher, onMount } from 'svelte';

    onMount(async () => {
        await import('ids-enterprise-wc/components/ids-input/ids-input');
    });
    
    const dispatch = createEventDispatcher();

    // Log the `<ids-input>` element when clicked
    const onInput = (e) => {
        if (e.target.tagName === 'IDS-INPUT') {
            console.dir(e.target.value);
            dispatch('input', { nativeEvent: e });
        }
    }

    export let id = '';
    export let label = '';
    export let value;
</script>

<ids-input
    id={`dynamic-input-${id}`}
    data-id={id}
    label={label}
    value={value}
    on:input={onInput}></ids-input>
