// angular-ids-wc/src/app/components/home/home.component.ts
import { Component, ViewChild, AfterViewInit } from '@angular/core';
import { routes } from '../../app-routing.module';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements AfterViewInit {
  public routes = routes;
  public categories: Array<any>;

  constructor() {
    this.categories = [
      { name: 'Form Inputs', icon: 'display' },
      { name: 'Navigation and Interaction', icon: 'map' },
      { name: 'Messages and Alerts', icon: 'success' },
      { name: 'Lists', icon: 'spreadsheet' },
      { name: 'Layouts', icon: 'project' },
      { name: 'Patterns', icon: 'design-mode' },
      { name: 'Charts and Visualizations', icon: 'line-bar-chart' },
      { name: 'Typography', icon: '' },
    ];
  }

  ngAfterViewInit() {
    console.log('Homepage init');
  }
}

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>

    <ng-container *ngFor="let category of categories">
      <ids-text font-size="24" type="h1">{{category.name}}</ids-text>
      <ids-block-grid>
        <ng-container *ngFor="let route of routes">
          <ids-block-grid-item *ngIf="route.data.category === category.name">
            <ids-card actionable="true" routerLink="{{route.path}}" target="_self" [attr.height]="100">
              <div slot="card-content">
                <ids-text font-size="16" type="h2" font-weight="bold">{{route.data.title}}</ids-text>
                <ids-text font-size="16" type="p">{{route.data.description}}</ids-text>
              </div>
            </ids-card>
          </ids-block-grid-item>
        </ng-container>
      </ids-block-grid>
    </ng-container>

  </ids-layout-grid-cell>
</ids-layout-grid>

// react-ids-wc/src/home/index.js
import React from 'react';

import { categories, routes } from '../settings/routes';

import './example.css';

const Home = () => {
  return (
    <ids-layout-grid auto="true" gap="md" class="main-list">
      <ids-layout-grid-cell>
        {categories.map(category => (
          <div key={category}>
            <ids-text type="h1" font-size="24">
              {category}
            </ids-text>
            <ids-layout-grid auto="true">
              <ids-layout-grid-cell>
                <ids-block-grid align="center">
                  {routes
                    .filter(route => route.category === category)
                    .map(({ route, title }) => (
                      <ids-block-grid-item key={route}>
                        <ids-card actionable="true" height="65" href={`/${route}`} target="_self">
                          <div slot="card-content">
                          <ids-text type="h2" font-size="16" font-weight="bold" color="slate-100">{title}</ids-text>
                          </div>
                        </ids-card>
                      </ids-block-grid-item>
                    ))}
                </ids-block-grid>
              </ids-layout-grid-cell>
            </ids-layout-grid>
          </div>
        ))}
      </ids-layout-grid-cell>
    </ids-layout-grid>
  );
};

export default Home;
