// react-ts-ids-wc/src/examples/ids-list-box/index.tsx
import React from 'react';
import 'ids-enterprise-wc/components/ids-list-box/ids-list-box';

const IdListBox = () => {
  return (
    <>
      <ids-layout-grid>
        <ids-text font-size="12" type="h1">
          List Box
        </ids-text>
      </ids-layout-grid>

      <ids-layout-grid>
        <ids-list-box>
          <ids-list-box-option>Option One</ids-list-box-option>
          <ids-list-box-option>Option Two</ids-list-box-option>
          <ids-list-box-option>Option Three</ids-list-box-option>
        </ids-list-box>
      </ids-layout-grid>
    </>
  );
};

export default IdListBox;

// sveltekit-ids-wc/src/routes/ids-list-box/index.svelte
<script lang="ts">
  import IdsDemoListing from '../../components/demo/IdsDemoListing.svelte';

  const listingData = [
    {
      link: 'example',
      type: 'Main Example',
      description: 'Simple usage of an IDS List Box within Svelte'
    }
  ];
</script>

<ids-layout-grid auto="true">
  <ids-text font-size="20" type="h1">Ids List Box Examples</ids-text>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <IdsDemoListing data={listingData} componentName="ids-list-box"></IdsDemoListing>
  </ids-layout-grid-cell>
</ids-layout-grid>
