// angular-ids-wc/src/app/components/ids-mask/demos/localized-dates/localized-dates.component.ts
import { Component, OnInit, AfterViewInit, ViewChild, ElementRef } from '@angular/core';

@Component({
  selector: 'app-localized-dates',
  templateUrl: './localized-dates.component.html',
  styleUrls: ['./localized-dates.component.css']
})
export class LocalizedDatesComponent implements OnInit, AfterViewInit {
  @ViewChild('pageContainer', { read: ElementRef }) pageContainer; 
  @ViewChild('maskDateShort', { read: ElementRef }) maskDateShort;
  @ViewChild('maskDateTime', { read: ElementRef }) maskDateTime;

  constructor() { }

  ngOnInit(): void {
    console.log('IdsMask localized-dates OnInit');
  }

  ngAfterViewInit(): void {
    const calendar = this.pageContainer.nativeElement.locale.calendar();

    // Configure Short Date input
    this.maskDateShort.nativeElement.mask = 'date';
    this.maskDateShort.nativeElement.placeholder = this.maskDateShort.nativeElement.maskOptions.format;

    // The default date format absorbed by the Mask Mixin from IdsLocale is "short".
    // For the timestamp field, we have to manually override the format set by the mixin.
    this.maskDateTime.nativeElement.mask = 'date';
    this.maskDateTime.nativeElement.maskOptions = {
      format: calendar.dateFormat.timestamp
    };
    this.maskDateTime.nativeElement.placeholder = this.maskDateTime.nativeElement.maskOptions.format;
  }

  handleLocaleChange() {
    const calendar = this.pageContainer.nativeElement.locale.calendar();
    const shortFormat = calendar.dateFormat.short;
    const timeFormat = calendar.dateFormat.timestamp;

    this.maskDateShort.nativeElement.value = '';
    this.maskDateShort.nativeElement.maskOptions.format = shortFormat;
    this.maskDateShort.nativeElement.placeholder = this.maskDateShort.nativeElement.maskOptions.format;

    this.maskDateTime.nativeElement.value = '';
    this.maskDateTime.nativeElement.maskOptions.format = timeFormat;
    this.maskDateTime.nativeElement.placeholder = this.maskDateTime.nativeElement.maskOptions.format;
  }
}

<ids-container 
  #pageContainer 
  language="en" 
  [locale]="'en-US'" 
  padding="8" 
  hidden
  (localechange)="handleLocaleChange()"
>
  <ids-theme-switcher mode="light" version="new"></ids-theme-switcher>
  
  <ids-layout-grid cols="3" gap="md">
    <ids-layout-grid-cell>
      <ids-text font-size="12" type="h1">Masked Inputs (Localized Dates)</ids-text>
    </ids-layout-grid-cell>
  </ids-layout-grid>

  <!-- <ids-layout-grid cols="1" gap="md">
    <ids-layout-grid-cell>
      <ids-dropdown id="locales" size="sm" label="Choose Locale" dirty-tracker="true" [value]="'en-US'">
        <ids-list-box>
          <ids-list-box-option [attr.value]="'en-US'">en-US</ids-list-box-option>
          <ids-list-box-option [attr.value]="'de-DE'"></ids-list-box-option>
          <ids-list-box-option [attr.value]="'ru-RU'">ru-RU</ids-list-box-option>
          <ids-list-box-option [attr.value]="'bg-BG'">bg-BG</ids-list-box-option>
          <ids-list-box-option [attr.value]="'he-IL'">he-IL</ids-list-box-option>
          <ids-list-box-option [attr.value]="'hr-HR'">hr-HR</ids-list-box-option>
          <ids-list-box-option [attr.value]="'ar-EG'">ar-EG</ids-list-box-option>
          <ids-list-box-option [attr.value]="'th-TH'">th-TH</ids-list-box-option>
          <ids-list-box-option [attr.value]="'zh-TW'">zh-TW</ids-list-box-option>
        </ids-list-box>
      </ids-dropdown>
    </ids-layout-grid-cell>
  </ids-layout-grid> -->

  <ids-layout-grid cols="3" gap="md">
    <ids-layout-grid-cell>
      <ids-input #maskDateShort id="mask-date-short" size="sm" label="Short Date"></ids-input>
    </ids-layout-grid-cell>
  </ids-layout-grid>

  <ids-layout-grid cols="3" gap="md">
    <ids-layout-grid-cell>
      <ids-input #maskDateTime id="mask-date-time" size="sm" label="Timestamp"></ids-input>
    </ids-layout-grid-cell>
  </ids-layout-grid>
</ids-container>

// sveltekit-ids-wc/src/routes/ids-mask/localized-dates.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  onMount(async () => {
    await import('ids-enterprise-wc/components/ids-input/ids-input');

    const pageContainer: any = document.querySelector('ids-container');
    let calendar = pageContainer.locale.calendar();

    // Configure Short Date input
    const dateInputShort: any = document.querySelector('#mask-date-short');
    dateInputShort.mask = 'date';
    dateInputShort.placeholder = dateInputShort.maskOptions.format;

    // The default date format absorbed by the Mask Mixin from IdsLocale is "short".
    // For the timestamp field, we have to manually override the format set by the mixin.
    const dateInputTime: any = document.querySelector('#mask-date-time');
    dateInputTime.mask = 'date';
    dateInputTime.maskOptions = {
      format: calendar.dateFormat.timestamp
    };
    dateInputTime.placeholder = dateInputTime.maskOptions.format;

    // Change locale on the date input when the Page container's locale changes
    pageContainer.addEventListener('localechange', () => {
      calendar = pageContainer.locale.calendar();
      const shortFormat = calendar.dateFormat.short;
      const timeFormat = calendar.dateFormat.timestamp;

      dateInputShort.value = '';
      dateInputShort.maskOptions.format = shortFormat;
      dateInputShort.placeholder = dateInputShort.maskOptions.format;

      dateInputTime.value = '';
      dateInputTime.maskOptions.format = timeFormat;
      dateInputTime.placeholder = dateInputTime.maskOptions.format;
    });
  });
</script>

<ids-layout-grid cols="3" gap="md">
  <ids-layout-grid-cell>
    <ids-text font-size="12" type="h1">Masked Inputs (Localized Dates)</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-layout-grid cols="3" gap="md">
  <ids-layout-grid-cell>
    <ids-input id="mask-date-short" size="sm" label="Short Date"></ids-input>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-layout-grid cols="3" gap="md">
  <ids-layout-grid-cell>
    <ids-input id="mask-date-time" size="sm" label="Timestamp"></ids-input>
  </ids-layout-grid-cell>
</ids-layout-grid>
