// angular-ids-wc/src/app/components/ids-data-label/ids-data-label.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-ids-data-label',
  templateUrl: './ids-data-label.component.html',
  styleUrls: ['./ids-data-label.component.css']
})
export class IdsDataLabelComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<ids-layout-grid cols="2" gap="md">
  <ids-layout-grid-cell>
    <ids-text font-size="20">Ids Data Label Examples</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-data-grid #table list-style="true"></ids-data-grid>

// react-ids-wc/src/examples/ids-data-label/index.js
import React from 'react';
import 'ids-enterprise-wc/components/ids-data-label/ids-data-label';

const IdsDataLabel = () => {
  return (
    <>
      <ids-layout-grid auto="true">
        <ids-layout-grid-cell>
          <ids-text font-size="12" type="h1">
            Data Label
          </ids-text>
        </ids-layout-grid-cell>
      </ids-layout-grid>
      <ids-layout-grid auto="true" gap="md">
        <ids-data-label label="Shipping to" label-position="left">
          Los Angeles, California 90001 USA
        </ids-data-label>
        <ids-data-label label="Shipping to">
          Los Angeles, California 90001 USA
        </ids-data-label>
      </ids-layout-grid>
    </>
  );
};

export default IdsDataLabel;
