// react-ids-wc/src/examples/ids-hyperlink/index.js
import React from 'react';

import 'ids-enterprise-wc/components/ids-layout-grid';
import 'ids-enterprise-wc/components/ids-text';
import 'ids-enterprise-wc/components/ids-hyperlink';

const IdsHyperlink = () => {
  return (
    <>
      <ids-layout-grid auto="true">
        <ids-text font-size="12" type="h1">
          Hyperlink
        </ids-text>
      </ids-layout-grid>
      <ids-layout-grid auto="true">
        <ids-layout-grid-cell>
          <ids-hyperlink href="http://www.example.com" target="_blank">
            Normal Link
          </ids-hyperlink>
        </ids-layout-grid-cell>
      </ids-layout-grid>

      <ids-layout-grid auto="true">
        <ids-text font-size="12" type="h1">
          Hyperlink (disabled)
        </ids-text>
      </ids-layout-grid>
      <ids-layout-grid auto="true">
        <ids-layout-grid-cell>
          <ids-hyperlink
            href="http://www.example.com"
            disabled="true"
            target="_blank"
          >
            Disabled Link
          </ids-hyperlink>
        </ids-layout-grid-cell>
      </ids-layout-grid>

      <ids-layout-grid auto="true">
        <ids-text font-size="12" type="h1">
          Hyperlink with Multiple Text Elements
        </ids-text>
      </ids-layout-grid>
      <ids-layout-grid auto="true">
        <ids-layout-grid-cell>
          <ids-hyperlink
            href="http://www.example.com"
            target="_blank"
            text-decoration="none"
          >
            <ids-text font-size="20" color="unset">
              Part One
            </ids-text>
            <ids-text font-size="14" color="unset">
              Part Two
            </ids-text>
          </ids-hyperlink>
        </ids-layout-grid-cell>
      </ids-layout-grid>
    </>
  );
};

export default IdsHyperlink;

// sveltekit-ids-wc/src/routes/ids-hyperlink/index.svelte
<script lang="ts">
  import IdsDemoListing from '../../components/demo/IdsDemoListing.svelte';

  const listingData = [
    {
      link: 'example',
      type: 'Main Example',
      description: 'Simple usage of an IDS HyperLink within Svelte'
    },
    {
      link: 'dynamic-example',
      type: 'Dynamic Example',
      description: 'IDS HyperLink wrapped in a Svelte component'
    }
  ];
</script>

<ids-layout-grid auto="true">
  <ids-text font-size="20" type="h1">Ids HyperLink Examples</ids-text>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <IdsDemoListing data={listingData} componentName="ids-hyperlink"></IdsDemoListing>
  </ids-layout-grid-cell>
</ids-layout-grid>
