// svelte-ids-wc/src/examples/ids-input/Index.svelte
<script>
    // @TODO: We currently can't import this component from `ids-enterprise-wc`
    // without causing a custom element error.
    import 'ids-enterprise-wc/components/ids-input';

    // Supporting Components
    import 'ids-enterprise-wc/components/ids-layout-grid';
    import 'ids-enterprise-wc/components/ids-text';
</script>

<style></style>

<ids-layout-grid>
    <ids-text font-size="12">Normal Input (Svelte)</ids-text>
</ids-layout-grid>

<ids-layout-grid>
    <ids-layout-grid-cell>
        <ids-input
            id="static-input"
            label="My Normal Input"
            type="text"
            value="I have contents"></ids-input>
    </ids-layout-grid-cell>
</ids-layout-grid>

// react-ids-wc/src/ids-examples/ids-input.js
import React from 'react';

import 'ids-enterprise-wc/components/ids-layout-grid';
import 'ids-enterprise-wc/components/ids-input';

function IdsInput() {
  const person = 'John Smith';

  function handleClickable(e) {
    console.log('Input Changed', e.target);
  }

  return (
    <React.Fragment>
      <ids-layout-grid>
        <ids-text font-size="12">Inputs</ids-text>
      </ids-layout-grid>

      <ids-layout-grid>
        <ids-layout-grid-cell>
          <ids-input label="Normal Input" value={ person } onChange={ handleClickable }></ids-input>
        </ids-layout-grid-cell>
      </ids-layout-grid>
    </React.Fragment>
  );
}

export default IdsInput;
