// sveltekit-ids-wc/src/routes/ids-text/+page.svelte
<script lang="ts">
  import IdsDemoListing from '../../components/demo/IdsDemoListing.svelte';

  const listingData = [
    {
      link: 'example',
      type: 'Main Example',
      description: 'Simple usage of an IDS Text within Svelte'
    }
  ];
</script>

<ids-layout-grid auto="true">
  <ids-text font-size="20" type="h1">Ids Text Examples</ids-text>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <IdsDemoListing data={listingData} componentId="ids-text"></IdsDemoListing>
  </ids-layout-grid-cell>
</ids-layout-grid>

// react-ids-wc/src/ids-examples/ids-text.js
import React from 'react';

import 'ids-enterprise-wc/components/ids-layout-grid';
import 'ids-enterprise-wc/components/ids-text';

function IdsText() {
  return (
    <React.Fragment>
      <ids-layout-grid>
        <ids-text font-size="12">Labels / Typography</ids-text>
      </ids-layout-grid>
      <ids-layout-grid>
        <ids-layout-grid-cell>
          <ids-text font-size="72">Size 72</ids-text>
          <ids-text font-size="60">Size 60</ids-text>
          <ids-text font-size="48">Size 48</ids-text>
          <ids-text font-size="40">Size 40</ids-text>
          <ids-text font-size="32">Size 32 (xl)</ids-text>
          <ids-text font-size="28">Size 28</ids-text>
          <ids-text font-size="24">Size 24 (lg)</ids-text>
          <ids-text font-size="20">Size 20</ids-text>
          <ids-text font-size="16">Size 16 (base)</ids-text>
          <ids-text font-size="14">Size 14 (sm)</ids-text>
          <ids-text font-size="12">Size 12 (xs)</ids-text>
          <ids-text font-size="10">Size 10</ids-text>
        </ids-layout-grid-cell>
      </ids-layout-grid>
    </React.Fragment>
  );
}

export default IdsText;
