// react-ts-ids-wc/src/examples/ids-tag/index.tsx
import React, { useRef, useEffect } from 'react';
import type IdsTagType from 'ids-enterprise-wc/components/ids-tag/ids-tag';
import 'ids-enterprise-wc/components/ids-tag/ids-tag';


const IdsTag = () => {
  const dismissibleTagRef = useRef<IdsTagType>();

  useEffect(() => {
    // Adding ref current element to variable to be able cleanup event listeners on unmount
    const dismissibleTag = dismissibleTagRef.current;

    // Event handler to be used in attach and cleanup event listener
    const handleTagRemove = (e: any) => {
      console.log('Tag Removed:', e?.detail?.elem?.textContent);
    };

    // Attach event listener
    dismissibleTag?.addEventListener('tagremove', handleTagRemove);

    // Cleanup event listener on React component unmount
    return () => {
      dismissibleTag?.removeEventListener('tagremove', handleTagRemove);
    }
  }, []);

  return (
    <>
      <ids-layout-grid auto="true">
        <ids-text font-size="12">Tags</ids-text>
      </ids-layout-grid>

      <ids-layout-grid auto="true">
        <ids-layout-grid-cell>
          <ids-tag>Normal Tag</ids-tag>
          <ids-tag color="secondary">Secondary Tags</ids-tag>
          <ids-tag color="success">Success Tag</ids-tag>
          <ids-tag color="info">Info Tag</ids-tag>
          <ids-tag color="warning">Warning Tag</ids-tag>
          <ids-tag color="error">Error Tag</ids-tag>
          <ids-tag color="#5CC6C7">Custom Tag Color</ids-tag>
          <ids-tag clickable="true">
            Clickable Tag
            <ids-icon icon="caret-right" size="xsmall"></ids-icon>
          </ids-tag>
          <ids-tag dismissible="true">
            <span>Dismissible Tag 1</span>
            <ids-icon
              icon="close"
              size="xsmall"
            ></ids-icon>
          </ids-tag>
          <ids-tag dismissible="true" ref={dismissibleTagRef}>
            <span>Dismissible Tag 2</span>
          </ids-tag>
        </ids-layout-grid-cell>
      </ids-layout-grid>
    </>
  );
};

export default IdsTag;

// angular-ids-wc/src/app/components/ids-tag/ids-tag.component.ts
import { Component, ViewChild, VERSION, AfterViewInit } from '@angular/core';
import IdsTag from 'ids-enterprise-wc/components/ids-tag/ids-tag.js';

@Component({
  selector: 'app-ids-tag',
  templateUrl: './ids-tag.component.html',
  styleUrls: ['./ids-tag.component.css']
})
export class IdsTagComponent implements AfterViewInit {
  @ViewChild('myTag') tag: IdsTag;

  public name = 'Angular ' + VERSION.major;
  public person = 'John Smith';
  public type = 'success';
  public tagList = [
    { type: '', name: 'Tag One' },
    { type: 'success', name: 'Tag Two' },
    { type: '', name: 'Tag Three' },
    { type: 'error', name: 'Tag Four' },
  ];

  constructor() { }

  ngAfterViewInit(): void {
    this.tag.nativeElement.color = 'success';
  }

  onTagRemove(details: CustomEvent) {
    console.log('tagremove fired', details, details.detail);
  }
}

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-text font-size="12">Tag with template reference variable</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>
<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-tag #myTag>{{name}}</ids-tag>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-text font-size="12">Tag with bound property</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>
<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-tag [color]="type" color="">{{person}}</ids-tag>
    <input [(ngModel)]="type" value="{{type}}"/>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-text font-size="12">Dismissible tag with keyboard events</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>
<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-tag>{{person}}<ids-icon icon="caret-right" size="small"></ids-icon></ids-tag>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-text font-size="12">Tag with events</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>
<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-tag dismissible="true" (tagremove)="onTagRemove($event)" (beforetagremove)="onTagRemove($event)">
      <span>Dismissible Tags</span>
    </ids-tag>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-text font-size="12">Tag list in a loop</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>
<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-tag *ngFor="let tag of tagList" [color]="tag.type">{{tag.name}}</ids-tag>
  </ids-layout-grid-cell>
</ids-layout-grid>
