// react-ids-wc/src/components/ids-tag/index.js
import React, { useRef, useEffect } from 'react';

import 'ids-enterprise-wc/components/ids-layout-grid';
// import 'ids-enterprise-wc/components/ids-text';
// import 'ids-enterprise-wc/components/ids-icon';
// import 'ids-enterprise-wc/components/ids-tag';

function IdsTag() {
  const reactInfoTagRef = useRef();
  const dismissibleTagRef = useRef();

  const reactInfoText = `React ${React.version}`;
  const person = 'John Smith';
  const type = 'error';

  function handleClickable(e) {
    console.log('Tag clicked:', e.target.parentNode.textContent);
  }

  useEffect(() => {
    reactInfoTagRef.current.color = 'success';
    dismissibleTagRef.current.addEventListener('tagremoved', e => {
      console.log('Tag Removed:', e.detail.elem.textContent);
    });
  });

  return (
    <>
      <ids-layout-grid>
        <ids-text font-size="12">Normal Tags</ids-text>
      </ids-layout-grid>

      <ids-layout-grid>
        <ids-layout-grid-cell>
          <ids-tag>Normal Tag</ids-tag>
          <ids-tag color="secondary">Secondary Tags</ids-tag>
          <ids-tag color="error">Error Tag</ids-tag>
          <ids-tag color="success">Success Tag</ids-tag>
          <ids-tag color="caution">Warning Tag</ids-tag>
          <ids-tag color="#EDE3FC">Custom Tag Color</ids-tag>
        </ids-layout-grid-cell>
      </ids-layout-grid>

      <ids-layout-grid>
        <ids-text font-size="12">Dynamic Tags</ids-text>
      </ids-layout-grid>
      <ids-layout-grid>
        <ids-layout-grid-cell>
          <ids-tag ref={ reactInfoTagRef }>{ reactInfoText }</ids-tag>
          <ids-tag color={ type }><span>{ person }</span></ids-tag>
          <ids-tag clickable="true" id="ids-clickable-tag">Clickable Tag
            <ids-icon icon="caret-right" size="small" onClick={ handleClickable }></ids-icon>
          </ids-tag>
          <ids-tag dismissible="true" ref={ dismissibleTagRef }><slot>{ person }</slot></ids-tag>
        </ids-layout-grid-cell>
      </ids-layout-grid>
    </>
  );
}

export default IdsTag;

// angular-ids-wc/src/app/components/ids-tag/ids-tag.component.ts
import { Component, ViewChild, VERSION, AfterViewInit } from '@angular/core';
import IdsTag from 'ids-enterprise-wc/components/ids-tag/ids-tag.js';

@Component({
  selector: 'app-ids-tag',
  templateUrl: './ids-tag.component.html',
  styleUrls: ['./ids-tag.component.css']
})
export class IdsTagComponent implements AfterViewInit {
  @ViewChild('myTag') tag: IdsTag;

  public name = 'Angular ' + VERSION.major;
  public person = 'John Smith';
  public type = 'success';
  public tagList = [
    { type: '', name: 'Tag One' },
    { type: 'success', name: 'Tag Two' },
    { type: '', name: 'Tag Three' },
    { type: 'error', name: 'Tag Four' },
  ];

  constructor() { }

  ngAfterViewInit(): void {
    this.tag.nativeElement.color = 'success';
  }

  onTagRemove(details: CustomEvent) {
    console.log('tagremove fired', details, details.detail);
  }
}

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-text font-size="12">Tag with template reference variable</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>
<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-tag #myTag>{{name}}</ids-tag>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-text font-size="12">Tag with bound property</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>
<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-tag [color]="type" color="">{{person}}</ids-tag>
    <input [(ngModel)]="type" value="{{type}}"/>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-text font-size="12">Dismissible tag with keyboard events</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>
<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-tag>{{person}}<ids-icon icon="caret-right" size="small"></ids-icon></ids-tag>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-text font-size="12">Tag with events</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>
<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-tag dismissible="true" (tagremove)="onTagRemove($event)" (beforetagremove)="onTagRemove($event)">
      <span>Dismissible Tags</span>
    </ids-tag>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-text font-size="12">Tag list in a loop</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>
<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-tag *ngFor="let tag of tagList" [color]="tag.type">{{tag.name}}</ids-tag>
  </ids-layout-grid-cell>
</ids-layout-grid>
