// sveltekit-ids-wc/src/routes/ids-checkbox/index.svelte
<ids-layout-grid auto="true">
  <ids-text font-size="20" type="h1">Ids Checkbox Examples</ids-text>
</ids-layout-grid>

<ids-layout-grid auto="true">
  <ids-layout-grid-cell>
    <ids-demo-listing label="Checkbox Examples" component-name="ids-checkbox"></ids-demo-listing>
  </ids-layout-grid-cell>
</ids-layout-grid>

// angular-ids-wc/src/app/components/ids-checkbox/ids-checkbox.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-ids-checkbox',
  templateUrl: './ids-checkbox.component.html',
  styleUrls: ['./ids-checkbox.component.css']
})
export class IdsCheckboxComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<ids-layout-grid cols="2" gap="md">
  <ids-layout-grid-cell>
    <ids-text font-size="20">Ids Checkbox Examples</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-data-grid #table list-style="true"></ids-data-grid>
