// sveltekit-ids-wc/src/routes/ids-mask/localized-numbers/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { deepClone } from '../../utils/deepClone';

  onMount(async () => {
    await import('ids-enterprise-wc/components/ids-input/ids-input');

    const pageContainer: any = document.querySelector('ids-container');
    // const dropdown: any = document.querySelector('ids-dropdown');

    // Uses the defined integer/decimal limits to create an IdsInput
    // `placeholder` definition based on the actual length of the mask.
    const createPlaceholder = (input: any) => {
      const ints = input.maskOptions.integerLimit;
      const decs = input.maskOptions.decimalLimit || 0;
      let placeholder = '';

      for (let i = 0; i < ints; i++) {
        placeholder += '1';
      }

      if (input.maskOptions.allowDecimal) {
        placeholder += input.maskOptions?.symbols?.decimal || '.';
        for (let i = 0; i < decs; i++) {
          placeholder += '1';
        }
      }

      // calling `input.mask()` directly doesn't include the locale,
      // since it's normally added by the IdsInput
      const opts = deepClone(input.maskOptions);
      opts.locale = input.locale;
      const maskArray = input.mask(placeholder, opts).mask;

      // Write a placeholder string based on a slightly-modified mask array
      // (removes "[]"" caret traps and replaces regex matchers with "#")
      input.placeholder = `${maskArray.map((el: any) => {
        if (typeof el !== 'string') {
          return '#';
        }
        if (el === '[]') {
          return '';
        }
        return el;
      }).join('')}`;
    };

    // ===================================================
    // Set basic rules on all input fields
    const allInputs: Array<any> = [...document.querySelectorAll('ids-input')];
    allInputs.forEach((input) => {
      input.textAlign = 'end';
      input.mask = 'number';
    });

    const allNegativeInputs: Array<any> = [...document.querySelectorAll('[id*="negative"]')];
    allNegativeInputs.forEach((input) => {
      input.maskOptions.allowNegative = true;
    });

    const allDecimalInputs: Array<any> = [...document.querySelectorAll('[id*="decimal"]')];
    allDecimalInputs.forEach((input) => {
      input.maskOptions.allowDecimal = true;
      input.maskOptions.decimalLimit = 2;
    });

    const allGroupInputs: Array<any> = [...document.querySelectorAll('[id*="group"]')];
    allGroupInputs.forEach((input) => {
      input.maskOptions.allowThousandsSeparator = true;
    });

    // ===================================================
    // Set limits on "thousands-length" inputs
    const allThousandsInputs: Array<any> = [...document.querySelectorAll('[id*="thousands"]')];
    allThousandsInputs.forEach((input) => {
      input.maskOptions.integerLimit = 4;
      createPlaceholder(input);
    });

    // Set limits on "millions-length" inputs
    const allMillionsInputs: Array<any> = [...document.querySelectorAll('[id*="millions"]')];
    allMillionsInputs.forEach((input) => {
      input.maskOptions.integerLimit = 7;
      createPlaceholder(input);
    });

    // Set limits on "billions-length" inputs
    const allBillionsInputs: Array<any> = [...document.querySelectorAll('[id*="billions"]')];
    allBillionsInputs.forEach((input) => {
      input.maskOptions.integerLimit = 10;
      createPlaceholder(input);
    });

    // Set limits on "quintillions-length" inputs
    const allQuintillionsInputs: Array<any> = [...document.querySelectorAll('[id*="quintillions"]')];
    allQuintillionsInputs.forEach((input) => {
      input.maskOptions.integerLimit = 18;
      if (input.id.includes('decimal')) {
        input.maskOptions.decimalLimit = 6;
      }
      createPlaceholder(input);
    });

    /*
    // ===================================================
    // Change the IdsContainer's locale setting when the dropdown is modified
    dropdown.addEventListener('change', async (e: any) => {
      await pageContainer.setLocale(e.target.value);
    });
    */

    // Change localized strings on all number inputs when the Page container's locale changes
    pageContainer.addEventListener('localechange', () => {
      allInputs.forEach((input) => {
        input.value = '';
        createPlaceholder(input);
      });
    });
  });
</script>

<ids-layout-grid cols="3" gap="md">
  <ids-layout-grid-cell>
    <ids-text font-size="12" type="h1">Masked Inputs (Localized Numbers) (Imported into Svelte)</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>

<!-- Thousands-length Inputs without groups -->
<ids-layout-grid cols="4" gap="md">
  <ids-layout-grid-cell>
    <ids-input id="mask-number-thousands" label="Thousands"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-thousands-negative" label="Thousands + Negative"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-thousands-decimal" label="Thousands + Decimal"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-thousands-decimal-negative" label="Thousands + Decimal + Negative"></ids-input>
  </ids-layout-grid-cell>
</ids-layout-grid>

<!-- Thousands-length Inputs with groups -->
<ids-layout-grid cols="4" gap="md">
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-thousands" label="Thousands + Groups"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-thousands-negative" label="Thousands + Groups + Negative"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-thousands-decimal" label="Thousands + Groups + Decimal"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-thousands-decimal-negative" label="Thousands + Groups + Decimal + Negative"></ids-input>
  </ids-layout-grid-cell>
</ids-layout-grid>

<!-- Millions-length Inputs without groups -->
<ids-layout-grid cols="4" gap="md">
  <ids-layout-grid-cell>
    <ids-input id="mask-number-millions" label="Millions"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-millions-negative" label="Millions + Negative"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-millions-decimal" label="Millions + Decimal"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-millions-decimal-negative" label="Millions + Decimal + Negative"></ids-input>
  </ids-layout-grid-cell>
</ids-layout-grid>

<!-- Millions-length Inputs with groups -->
<ids-layout-grid cols="4" gap="md">
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-millions" label="Millions + Groups"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-millions-negative" label="Millions + Groups + Negative"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-millions-decimal" label="Millions + Groups + Decimal"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-millions-decimal-negative" label="Millions + Groups + Decimal + Negative"></ids-input>
  </ids-layout-grid-cell>
</ids-layout-grid>

<!-- Billions-length Inputs without groups -->
<ids-layout-grid cols="4" gap="md">
  <ids-layout-grid-cell>
    <ids-input id="mask-number-billions" label="Billions"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-billions-negative" label="Billions + Negative"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-billions-decimal" label="Billions + Decimal"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-billions-decimal-negative" label="Billions + Decimal + Negative"></ids-input>
  </ids-layout-grid-cell>
</ids-layout-grid>

<!-- Billions-length Inputs with groups -->
<ids-layout-grid cols="4" gap="md">
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-billions" label="Billions + Groups"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-billions-negative" label="Billions + Groups + Negative"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-billions-decimal" label="Billions + Groups + Decimal"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-billions-decimal-negative" label="Billions + Groups + Decimal + Negative">
    </ids-input>
  </ids-layout-grid-cell>
</ids-layout-grid>

<!-- Quintillions-length Inputs without groups -->
<ids-layout-grid cols="4" gap="md">
  <ids-layout-grid-cell>
    <ids-input id="mask-number-quintillions" label="Quintillions"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-quintillions-negative" label="Quintillions + Negative"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-quintillions-decimal" label="Quintillions + Decimal"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-quintillions-decimal-negative" label="Quintillions + Decimal + Negative"></ids-input>
  </ids-layout-grid-cell>
</ids-layout-grid>

<!-- Quintillions-length Inputs with groups -->
<ids-layout-grid cols="4" gap="md">
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-quintillions" label="Quintillions + Groups"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-quintillions-negative" label="Quintillions + Groups + Negative"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-quintillions-decimal" label="Quintillions + Groups + Decimal"></ids-input>
  </ids-layout-grid-cell>
  <ids-layout-grid-cell>
    <ids-input id="mask-number-groups-quintillions-decimal-negative" label="Quintillions + Groups + Decimal + Negative">
    </ids-input>
  </ids-layout-grid-cell>
</ids-layout-grid>

// angular-ids-wc/src/app/components/ids-mask/demos/localized-numbers/localized-numbers.component.ts
import { Component, OnInit, AfterViewInit, ViewChild, ViewChildren, ElementRef, QueryList } from '@angular/core';
import IdsInput from 'ids-enterprise-wc/components/ids-input/ids-input';
// import { deepClone } from 'ids-enterprise-wc/utils/ids-deep-clone-utils/ids-deep-clone-utils';

// Store the references to avoid circular reference problems
const refs: Array<any> = [];
const refsNew: Array<any> = [];

/**
 * Deep clone an array creating a new array
 * @param {any} this The array to clone
 * @param {Array} arr The array to clone
 * @param {Function} fn The functional call back used for recursion
 * @returns {Array} The array's clone
 */
export function deepCloneArray(this: any, arr: any, fn?: any) {
  const keys = Object.keys(arr);
  const arrClone = new Array(keys.length);

  for (let i = 0; i < keys.length; i += 1) {
    const k: any = keys[i];
    const cur = arr[k];

    if (typeof cur !== 'object' || cur === null) {
      arrClone[k] = cur;
    } else if (cur instanceof Date) {
      arrClone[k] = new Date(cur);
    } else {
      const index = refs.indexOf(cur);
      if (index !== -1) {
        arrClone[k] = refsNew[index];
      } else {
        arrClone[k] = fn.call(this, cur);
      }
    }
  }
  return arrClone;
}

/**
 * Deep clone an object creating a new object
 * @param {object|Array} obj The object or array to clone
 * @returns {object|Array} The object/array's clone
 */
 export function deepClone(obj: any) {
  if (typeof obj !== 'object' || obj === null) {
    return obj;
  }

  if (obj instanceof Date) {
    return new Date(obj);
  }

  if (Array.isArray(obj)) {
    return deepCloneArray(obj, deepClone);
  }

  const objClone: any = {};
  refs.push(obj);
  refsNew.push(objClone);

  for (const k in obj) {
    if (Object.hasOwnProperty.call(obj, k) === false) {
      continue;
    }

    const cur = obj[k];
    if (typeof cur !== 'object' || cur === null) {
      objClone[k] = cur;
    } else if (cur instanceof Date) {
      objClone[k] = new Date(cur);
    } else {
      const i = refs.indexOf(cur);
      if (i !== -1) {
        objClone[k] = refsNew[i];
      } else {
        objClone[k] = deepClone(cur);
      }
    }
  }
  refs.pop();
  refsNew.pop();
  return objClone;
}

@Component({
  selector: 'app-localized-numbers',
  templateUrl: './localized-numbers.component.html',
  styleUrls: ['./localized-numbers.component.css']
})
export class LocalizedNumbersComponent implements OnInit, AfterViewInit {
  @ViewChildren('idsInput', { read: ElementRef }) idsInput: QueryList<any>;
  @ViewChild('pageContainer', { read: ElementRef }) pageContainer;

  constructor() { }

  ngOnInit(): void {
    console.log('IdsMask localized-numbers OnInit');
  }

  ngAfterViewInit(): void {
    // Set basic rules on all input fields
    this.idsInput.toArray().forEach((input) => {
      input.nativeElement.textAlign = 'right';
      input.nativeElement.mask = 'number';
    });

    const allNegativeInputs = this.idsInput.toArray().filter(input => input.nativeElement.getAttribute('id').includes('negative') )
    allNegativeInputs.forEach((input) => {
      input.nativeElement.maskOptions.allowNegative = true;
    });

    const allDecimalInputs = this.idsInput.toArray().filter(input => input.nativeElement.getAttribute('id').includes('decimal'));
    allDecimalInputs.forEach((input) => {
      input.nativeElement.maskOptions.allowDecimal = true;
      input.nativeElement.maskOptions.decimalLimit = 2;
    });

    const allGroupInputs = this.idsInput.toArray().filter(input => input.nativeElement.getAttribute('id').includes('group'));
    allGroupInputs.forEach((input) => {
      input.nativeElement.maskOptions.allowThousandsSeparator = true;
    });

    // Set limits on "thousands-length" inputs
    const allThousandsInputs = this.idsInput.toArray().filter(input => input.nativeElement.getAttribute('id').includes('thousands'));
    allThousandsInputs.forEach((input) => {
      input.nativeElement.maskOptions.integerLimit = 4;
      this.createPlaceholder(input.nativeElement);
    });

    // Set limits on "millions-length" inputs
    const allMillionsInputs = this.idsInput.toArray().filter(input => input.nativeElement.getAttribute('id').includes('millions'));
    allMillionsInputs.forEach((input) => {
      input.nativeElement.maskOptions.integerLimit = 7;
      this.createPlaceholder(input.nativeElement);
    });

    // Set limits on "billions-length" inputs
    const allBillionsInputs = this.idsInput.toArray().filter(input => input.nativeElement.getAttribute('id').includes('billions'));
    allBillionsInputs.forEach((input) => {
      input.nativeElement.maskOptions.integerLimit = 10;
      this.createPlaceholder(input.nativeElement);
    });

    // Set limits on "quintillions-length" inputs
    const allQuintillionsInputs = this.idsInput.toArray().filter(input => input.nativeElement.getAttribute('id').includes('quintillions'));
    allQuintillionsInputs.forEach((input) => {
      input.nativeElement.maskOptions.integerLimit = 18;
      if (input.nativeElement.id.includes('decimal')) {
        input.nativeElement.maskOptions.decimalLimit = 6;
      }
      this.createPlaceholder(input.nativeElement);
    });
    
    // Change localized strings on all number inputs when the Page container's locale changes
    this.pageContainer.nativeElement.addEventListener('localechange', () => {
      this.idsInput.toArray().forEach((input) => {
        input.nativeElement.value = '';
        this.createPlaceholder(input.nativeElement);
      });
    });
  }

  // Uses the defined integer/decimal limits to create an IdsInput
  // `placeholder` definition based on the actual length of the mask.
  createPlaceholder = (input: any) => {
    const ints = input.maskOptions.integerLimit;
    const decs = input.maskOptions.decimalLimit || 0;
    let placeholder = '';

    for (let i = 0; i < ints; i++) {
      placeholder += '1';
    }

    if (input.maskOptions.allowDecimal) {
      placeholder += input.maskOptions.symbols.decimal;
      for (let i = 0; i < decs; i++) {
        placeholder += '1';
      }
    }

    // calling `input.mask()` directly doesn't include the locale,
    // since it's normally added by the IdsInput
    const opts = deepClone(input.maskOptions);
    opts.locale = input.locale;
    const maskArray = input.mask(placeholder, opts).mask;

    // Write a placeholder string based on a slightly-modified mask array
    // (removes "[]"" caret traps and replaces regex matchers with "#")
    input.placeholder = `${maskArray.map((el: any) => {
      if (typeof el !== 'string') {
        return '#';
      }
      if (el === '[]') {
        return '';
      }
      return el;
    }).join('')}`;
  };
}

<ids-container #pageContainer language="en" locale="en-US" padding="8" hidden>
  <ids-theme-switcher mode="light" version="new"></ids-theme-switcher>
  
  <ids-layout-grid cols="3" gap="md">
    <ids-layout-grid-cell>
      <ids-text font-size="12" type="h1">Masked Inputs (Localized Numbers)</ids-text>
    </ids-layout-grid-cell>
  </ids-layout-grid>

  <!-- Thousands-length Inputs without groups -->
  <ids-layout-grid cols="4" gap="md">
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-thousands" label="Thousands"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-thousands-negative" label="Thousands + Negative"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-thousands-decimal" label="Thousands + Decimal"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-thousands-decimal-negative" label="Thousands + Decimal + Negative"></ids-input>
    </ids-layout-grid-cell>
  </ids-layout-grid>

  <!-- Thousands-length Inputs with groups -->
  <ids-layout-grid cols="4" gap="md">
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-thousands" label="Thousands + Groups"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-thousands-negative" label="Thousands + Groups + Negative"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-thousands-decimal" label="Thousands + Groups + Decimal"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-thousands-decimal-negative" label="Thousands + Groups + Decimal + Negative"></ids-input>
    </ids-layout-grid-cell>
  </ids-layout-grid>

  <!-- Millions-length Inputs without groups -->
  <ids-layout-grid cols="4" gap="md">
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-millions" label="Millions"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-millions-negative" label="Millions + Negative"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-millions-decimal" label="Millions + Decimal"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-millions-decimal-negative" label="Millions + Decimal + Negative"></ids-input>
    </ids-layout-grid-cell>
  </ids-layout-grid>

  <!-- Millions-length Inputs with groups -->
  <ids-layout-grid cols="4" gap="md">
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-millions" label="Millions + Groups"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-millions-negative" label="Millions + Groups + Negative"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-millions-decimal" label="Millions + Groups + Decimal"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-millions-decimal-negative" label="Millions + Groups + Decimal + Negative"></ids-input>
    </ids-layout-grid-cell>
  </ids-layout-grid>

  <!-- Billions-length Inputs without groups -->
  <ids-layout-grid cols="4" gap="md">
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-billions" label="Billions"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-billions-negative" label="Billions + Negative"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-billions-decimal" label="Billions + Decimal"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-billions-decimal-negative" label="Billions + Decimal + Negative"></ids-input>
    </ids-layout-grid-cell>
  </ids-layout-grid>

  <!-- Billions-length Inputs with groups -->
  <ids-layout-grid cols="4" gap="md">
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-billions" label="Billions + Groups"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-billions-negative" label="Billions + Groups + Negative"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-billions-decimal" label="Billions + Groups + Decimal"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-billions-decimal-negative" label="Billions + Groups + Decimal + Negative">
      </ids-input>
    </ids-layout-grid-cell>
  </ids-layout-grid>

  <!-- Quintillions-length Inputs without groups -->
  <ids-layout-grid cols="4" gap="md">
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-quintillions" label="Quintillions"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-quintillions-negative" label="Quintillions + Negative"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-quintillions-decimal" label="Quintillions + Decimal"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-quintillions-decimal-negative" label="Quintillions + Decimal + Negative"></ids-input>
    </ids-layout-grid-cell>
  </ids-layout-grid>

  <!-- Quintillions-length Inputs with groups -->
  <ids-layout-grid cols="4" gap="md">
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-quintillions" label="Quintillions + Groups"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-quintillions-negative" label="Quintillions + Groups + Negative"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-quintillions-decimal" label="Quintillions + Groups + Decimal"></ids-input>
    </ids-layout-grid-cell>
    <ids-layout-grid-cell>
      <ids-input #idsInput id="mask-number-groups-quintillions-decimal-negative" label="Quintillions + Groups + Decimal + Negative">
      </ids-input>
    </ids-layout-grid-cell>
  </ids-layout-grid>
</ids-container>
