// react-ids-wc/src/examples/ids-date-picker/index.js
import React from 'react';
import 'ids-enterprise-wc/components/ids-date-picker/ids-date-picker';


const IdsDatePicker = () => {
  return (
    <>
      <ids-layout-grid auto="true">
        <ids-text font-size="12" type="h1">
          Date Picker
        </ids-text>
      </ids-layout-grid>
      <ids-layout-grid auto="true">
        <ids-layout-grid-cell>
          <ids-date-picker label="Date Field"></ids-date-picker>
        </ids-layout-grid-cell>
      </ids-layout-grid>
    </>
  );
};

export default IdsDatePicker;

// angular-ids-wc/src/app/components/ids-date-picker/ids-date-picker.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-ids-date-picker',
  templateUrl: './ids-date-picker.component.html',
  styleUrls: ['./ids-date-picker.component.css']
})
export class IdsDatePickerComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<ids-layout-grid cols="2" gap="md">
  <ids-layout-grid-cell>
    <ids-text font-size="20">Ids Date Picker Examples</ids-text>
  </ids-layout-grid-cell>
</ids-layout-grid>

<ids-data-grid #table list-style="true"></ids-data-grid>
